blueprint:
  name: "Bambu Lab 3D Printer Cost Notification (HA Native, Optional Stats)"
  description: >
    Calculate filament, electricity, and depreciation costs for each Bambu Lab 3D print,
    and send a native Home Assistant notification (notify.*) with the details and print image
    when the job completes. All-time stats and depreciation line can be toggled on/off.
  domain: automation
  input:
    printer_status_sensor:
      name: Printer Status Sensor
      description: "sensor.<printer>_print_status (HACS Bambu Lab integration)"
      selector:
        entity:
          integration: bambu_lab
          domain: sensor

    printer_cover_image:
      name: Print Cover Image
      description: "Image entity from Bambu integration (optional). Leave blank to send only text."
      default: ~
      selector:
        entity:
          integration: bambu_lab
          domain: image

    printer_start_time_sensor:
      name: Printer Start Time Sensor
      description: "sensor.<printer>_start_time (HACS Bambu Lab integration)"
      selector:
        entity:
          integration: bambu_lab
          domain: sensor

    printer_end_time_sensor:
      name: Printer End Time Sensor
      description: "sensor.<printer>_end_time (HACS Bambu Lab integration)"
      selector:
        entity:
          integration: bambu_lab
          domain: sensor

    print_weight_sensor:
      name: Print Weight Sensor/Helper
      description: "Weight in grams (integration sensor or input_number)."
      selector:
        entity:
          filter:
            - domain: sensor
            - domain: input_number

    print_length_sensor:
      name: Print Length Sensor/Helper (optional)
      description: "Length in mm or m (integration sensor or input_number). Leave empty if not available."
      default: ~
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
            - domain: input_number

    total_usage_sensor:
      name: Total Usage Hours Sensor
      description: "sensor.
